"""Smoke + win/loss path tests for miniatari-atlantis-v0."""
from __future__ import annotations

import glyphbench  # noqa: F401  # registers all envs
from glyphbench.core import make_env


def test_env_constructs():
    env = make_env("glyphbench/miniatari-atlantis-v0")
    obs, info = env.reset(seed=0)
    assert obs is not None
    assert info["env_id"] == "glyphbench/miniatari-atlantis-v0"


def test_env_steps():
    env = make_env("glyphbench/miniatari-atlantis-v0")
    env.reset(seed=0)
    obs, reward, terminated, truncated, info = env.step(0)
    assert isinstance(reward, float)
    assert isinstance(terminated, bool)
    assert isinstance(truncated, bool)


# Scripted "highest raider in each turret column wins priority" defense
# that clears all 3 waves on seed=0. Generated by a column-priority bot.
# Pinned for determinism. With the pre-fix sentinel bug (`target_y=-1`
# default, raiders at y=-2/-4 silently skipped) this sequence would
# never clear a wave; the new -inf sentinel makes off-screen raiders
# selectable, which is exactly what this win path exercises.
_ATLANTIS_WIN_SEQUENCE_SEED0 = [
    "LEFT", "CENTER", "RIGHT", "LEFT", "CENTER", "LEFT", "RIGHT",
    "LEFT", "LEFT", "LEFT", "CENTER", "RIGHT", "CENTER", "RIGHT",
    "CENTER",
]


def test_atlantis_win_path() -> None:
    """Scripted column-priority defense clears all 3 waves on seed=0."""
    env = make_env("glyphbench/miniatari-atlantis-v0")
    env.reset(seed=0)
    cumulative = 0.0
    won = False
    terminated = False
    info: dict = {}
    for name in _ATLANTIS_WIN_SEQUENCE_SEED0:
        action = env.action_spec.names.index(name)
        _, reward, terminated, truncated, info = env.step(action)
        cumulative += reward
        if terminated or truncated:
            won = bool(info.get("won"))
            break
    assert terminated, "win sequence must terminate the episode"
    assert won, "win sequence must set won=True"
    assert 0.0 < cumulative <= 1.0 + 1e-6, (
        f"cumulative {cumulative} not in (0, 1]"
    )


def test_atlantis_loss_path() -> None:
    """NOOP-only lets the raiders march into the city => -1 terminal."""
    env = make_env("glyphbench/miniatari-atlantis-v0")
    env.reset(seed=0)
    noop = env.action_spec.names.index("NOOP")
    cumulative = 0.0
    won = True
    terminated = False
    info: dict = {}
    for _ in range(env.max_turns):
        _, reward, terminated, truncated, info = env.step(noop)
        cumulative += reward
        if terminated or truncated:
            won = bool(info.get("won"))
            break
    assert terminated, "NOOP-only must terminate via city breach"
    assert not won, "loss path must set won=False"
    assert -1.0 - 1e-6 <= cumulative, f"cumulative {cumulative} below -1"


def test_atlantis_full_wave_includes_offscreen_raiders() -> None:
    """Regression: the column shot must select raiders at y < 0
    (previously a `target_y=-1` sentinel silently skipped them)."""
    env = make_env("glyphbench/miniatari-atlantis-v0")
    env.reset(seed=0)
    # Each wave has exactly 5 raiders, regardless of stack offsets above
    # the visible field.
    assert len(env._raiders) == 5
    # Confirm at least one raider starts at y < 0 (off-screen) for the
    # original bug to have been observable.
    assert any(ry < 0 for _rx, ry in env._raiders)
