"""Smoke + win/loss path tests for miniatari-alien-v0."""
from __future__ import annotations

import glyphbench  # noqa: F401  # registers all envs
from glyphbench.core import make_env


def test_env_constructs():
    env = make_env("glyphbench/miniatari-alien-v0")
    obs, info = env.reset(seed=0)
    assert obs is not None
    assert info["env_id"] == "glyphbench/miniatari-alien-v0"


def test_env_steps():
    env = make_env("glyphbench/miniatari-alien-v0")
    env.reset(seed=0)
    obs, reward, terminated, truncated, info = env.step(0)
    assert isinstance(reward, float)
    assert isinstance(terminated, bool)
    assert isinstance(truncated, bool)


# Captured action sequence that reliably clears all 4 aliens on seed=0
# under the current dynamics. Generated by a kite-and-fire bot; pinned
# here so the win path is deterministic and fast (38 steps).
_ALIEN_WIN_SEQUENCE_SEED0 = [
    "RIGHT", "RIGHT", "UP", "FIRE", "UP", "LEFT", "RIGHT", "LEFT",
    "RIGHT", "RIGHT", "LEFT", "RIGHT", "RIGHT", "LEFT", "RIGHT",
    "LEFT", "FIRE", "UP", "LEFT", "UP", "DOWN", "RIGHT", "LEFT",
    "RIGHT", "RIGHT", "LEFT", "RIGHT", "LEFT", "FIRE", "UP", "UP",
    "UP", "UP", "RIGHT", "LEFT", "RIGHT", "LEFT", "FIRE",
]


def test_alien_win_path() -> None:
    """Scripted action sequence on seed=0 clears all 4 aliens.

    Asserts terminated=True, won=True, 0 < cumulative <= 1.0."""
    env = make_env("glyphbench/miniatari-alien-v0")
    env.reset(seed=0)
    cumulative = 0.0
    won = False
    terminated = False
    info: dict = {}
    for name in _ALIEN_WIN_SEQUENCE_SEED0:
        action = env.action_spec.names.index(name)
        _, reward, terminated, truncated, info = env.step(action)
        cumulative += reward
        if terminated or truncated:
            won = bool(info.get("won"))
            break
    assert terminated, "win sequence must terminate the episode"
    assert won, "win sequence must set won=True"
    assert 0.0 < cumulative <= 1.0 + 1e-6, (
        f"cumulative {cumulative} not in (0, 1]"
    )


def test_alien_loss_path() -> None:
    """NOOP-only run lets aliens chase and catch the player => -1 terminal."""
    env = make_env("glyphbench/miniatari-alien-v0")
    env.reset(seed=0)
    noop = env.action_spec.names.index("NOOP")
    cumulative = 0.0
    won = True
    terminated = False
    info: dict = {}
    for _ in range(env.max_turns):
        _, reward, terminated, truncated, info = env.step(noop)
        cumulative += reward
        if terminated or truncated:
            won = bool(info.get("won"))
            break
    assert terminated, "NOOP-only must terminate via alien catch"
    assert not won, "loss path must set won=False"
    assert -1.0 - 1e-6 <= cumulative, f"cumulative {cumulative} below -1"
