"""MiniGrid suite. Importing this module registers all MiniGrid envs with gym."""

from atlas_rl.core.registry import register_env

register_env(
    "atlas_rl/minigrid-empty-5x5-v0",
    "atlas_rl.envs.minigrid.empty:MiniGridEmpty5x5Env",
    max_episode_steps=None,
)
register_env(
    "atlas_rl/minigrid-empty-6x6-v0",
    "atlas_rl.envs.minigrid.empty:MiniGridEmpty6x6Env",
    max_episode_steps=None,
)
register_env(
    "atlas_rl/minigrid-empty-8x8-v0",
    "atlas_rl.envs.minigrid.empty:MiniGridEmpty8x8Env",
    max_episode_steps=None,
)
register_env(
    "atlas_rl/minigrid-empty-16x16-v0",
    "atlas_rl.envs.minigrid.empty:MiniGridEmpty16x16Env",
    max_episode_steps=None,
)
register_env(
    "atlas_rl/minigrid-empty-random-5x5-v0",
    "atlas_rl.envs.minigrid.empty:MiniGridEmptyRandom5x5Env",
    max_episode_steps=None,
)
register_env(
    "atlas_rl/minigrid-empty-random-6x6-v0",
    "atlas_rl.envs.minigrid.empty:MiniGridEmptyRandom6x6Env",
    max_episode_steps=None,
)
register_env(
    "atlas_rl/minigrid-doorkey-5x5-v0",
    "atlas_rl.envs.minigrid.doorkey:MiniGridDoorKey5x5Env",
    max_episode_steps=None,
)
register_env(
    "atlas_rl/minigrid-doorkey-6x6-v0",
    "atlas_rl.envs.minigrid.doorkey:MiniGridDoorKey6x6Env",
    max_episode_steps=None,
)
register_env(
    "atlas_rl/minigrid-doorkey-8x8-v0",
    "atlas_rl.envs.minigrid.doorkey:MiniGridDoorKey8x8Env",
    max_episode_steps=None,
)
register_env(
    "atlas_rl/minigrid-doorkey-16x16-v0",
    "atlas_rl.envs.minigrid.doorkey:MiniGridDoorKey16x16Env",
    max_episode_steps=None,
)
register_env(
    "atlas_rl/minigrid-fourrooms-v0",
    "atlas_rl.envs.minigrid.fourrooms:MiniGridFourRoomsEnv",
    max_episode_steps=None,
)
register_env(
    "atlas_rl/minigrid-multiroom-n2-s4-v0",
    "atlas_rl.envs.minigrid.multiroom:MiniGridMultiRoomN2S4Env",
    max_episode_steps=None,
)
register_env(
    "atlas_rl/minigrid-multiroom-n4-s5-v0",
    "atlas_rl.envs.minigrid.multiroom:MiniGridMultiRoomN4S5Env",
    max_episode_steps=None,
)
register_env(
    "atlas_rl/minigrid-multiroom-n6-v0",
    "atlas_rl.envs.minigrid.multiroom:MiniGridMultiRoomN6Env",
    max_episode_steps=None,
)
