"""MiniGrid suite. Importing this module registers all MiniGrid envs with gym."""

from atlas_rl.core.registry import register_env

register_env(
    "atlas_rl/minigrid-empty-5x5-v0",
    "atlas_rl.envs.minigrid.empty:MiniGridEmpty5x5Env",
    max_episode_steps=None,
)
register_env(
    "atlas_rl/minigrid-empty-6x6-v0",
    "atlas_rl.envs.minigrid.empty:MiniGridEmpty6x6Env",
    max_episode_steps=None,
)
register_env(
    "atlas_rl/minigrid-empty-8x8-v0",
    "atlas_rl.envs.minigrid.empty:MiniGridEmpty8x8Env",
    max_episode_steps=None,
)
register_env(
    "atlas_rl/minigrid-empty-16x16-v0",
    "atlas_rl.envs.minigrid.empty:MiniGridEmpty16x16Env",
    max_episode_steps=None,
)
register_env(
    "atlas_rl/minigrid-empty-random-5x5-v0",
    "atlas_rl.envs.minigrid.empty:MiniGridEmptyRandom5x5Env",
    max_episode_steps=None,
)
register_env(
    "atlas_rl/minigrid-empty-random-6x6-v0",
    "atlas_rl.envs.minigrid.empty:MiniGridEmptyRandom6x6Env",
    max_episode_steps=None,
)
register_env(
    "atlas_rl/minigrid-doorkey-5x5-v0",
    "atlas_rl.envs.minigrid.doorkey:MiniGridDoorKey5x5Env",
    max_episode_steps=None,
)
register_env(
    "atlas_rl/minigrid-doorkey-6x6-v0",
    "atlas_rl.envs.minigrid.doorkey:MiniGridDoorKey6x6Env",
    max_episode_steps=None,
)
register_env(
    "atlas_rl/minigrid-doorkey-8x8-v0",
    "atlas_rl.envs.minigrid.doorkey:MiniGridDoorKey8x8Env",
    max_episode_steps=None,
)
register_env(
    "atlas_rl/minigrid-doorkey-16x16-v0",
    "atlas_rl.envs.minigrid.doorkey:MiniGridDoorKey16x16Env",
    max_episode_steps=None,
)
register_env(
    "atlas_rl/minigrid-fourrooms-v0",
    "atlas_rl.envs.minigrid.fourrooms:MiniGridFourRoomsEnv",
    max_episode_steps=None,
)
register_env(
    "atlas_rl/minigrid-multiroom-n2-s4-v0",
    "atlas_rl.envs.minigrid.multiroom:MiniGridMultiRoomN2S4Env",
    max_episode_steps=None,
)
register_env(
    "atlas_rl/minigrid-multiroom-n4-s5-v0",
    "atlas_rl.envs.minigrid.multiroom:MiniGridMultiRoomN4S5Env",
    max_episode_steps=None,
)
register_env(
    "atlas_rl/minigrid-multiroom-n6-v0",
    "atlas_rl.envs.minigrid.multiroom:MiniGridMultiRoomN6Env",
    max_episode_steps=None,
)
register_env(
    "atlas_rl/minigrid-unlock-v0",
    "atlas_rl.envs.minigrid.unlock:MiniGridUnlockEnv",
    max_episode_steps=None,
)
register_env(
    "atlas_rl/minigrid-unlockpickup-v0",
    "atlas_rl.envs.minigrid.unlock:MiniGridUnlockPickupEnv",
    max_episode_steps=None,
)
register_env(
    "atlas_rl/minigrid-keycorridor-s3r1-v0",
    "atlas_rl.envs.minigrid.keycorridor:MiniGridKeyCorridorS3R1Env",
    max_episode_steps=None,
)
register_env(
    "atlas_rl/minigrid-keycorridor-s3r2-v0",
    "atlas_rl.envs.minigrid.keycorridor:MiniGridKeyCorridorS3R2Env",
    max_episode_steps=None,
)
register_env(
    "atlas_rl/minigrid-keycorridor-s3r3-v0",
    "atlas_rl.envs.minigrid.keycorridor:MiniGridKeyCorridorS3R3Env",
    max_episode_steps=None,
)
register_env(
    "atlas_rl/minigrid-keycorridor-s4r3-v0",
    "atlas_rl.envs.minigrid.keycorridor:MiniGridKeyCorridorS4R3Env",
    max_episode_steps=None,
)
register_env(
    "atlas_rl/minigrid-keycorridor-s5r3-v0",
    "atlas_rl.envs.minigrid.keycorridor:MiniGridKeyCorridorS5R3Env",
    max_episode_steps=None,
)
register_env(
    "atlas_rl/minigrid-keycorridor-s6r3-v0",
    "atlas_rl.envs.minigrid.keycorridor:MiniGridKeyCorridorS6R3Env",
    max_episode_steps=None,
)
register_env(
    "atlas_rl/minigrid-lockedroom-v0",
    "atlas_rl.envs.minigrid.lockedroom:MiniGridLockedRoomEnv",
    max_episode_steps=None,
)
register_env(
    "atlas_rl/minigrid-blockedunlockpickup-v0",
    "atlas_rl.envs.minigrid.lockedroom:MiniGridBlockedUnlockPickupEnv",
    max_episode_steps=None,
)
register_env(
    "atlas_rl/minigrid-distshift1-v0",
    "atlas_rl.envs.minigrid.distshift:MiniGridDistShift1Env",
    max_episode_steps=None,
)
register_env(
    "atlas_rl/minigrid-distshift2-v0",
    "atlas_rl.envs.minigrid.distshift:MiniGridDistShift2Env",
    max_episode_steps=None,
)
register_env(
    "atlas_rl/minigrid-lavagap-s5-v0",
    "atlas_rl.envs.minigrid.lavagap:MiniGridLavaGapS5Env",
    max_episode_steps=None,
)
register_env(
    "atlas_rl/minigrid-lavagap-s6-v0",
    "atlas_rl.envs.minigrid.lavagap:MiniGridLavaGapS6Env",
    max_episode_steps=None,
)
register_env(
    "atlas_rl/minigrid-lavagap-s7-v0",
    "atlas_rl.envs.minigrid.lavagap:MiniGridLavaGapS7Env",
    max_episode_steps=None,
)
register_env(
    "atlas_rl/minigrid-crossing-n1-v0",
    "atlas_rl.envs.minigrid.crossing:MiniGridCrossingN1Env",
    max_episode_steps=None,
)
register_env(
    "atlas_rl/minigrid-crossing-n2-v0",
    "atlas_rl.envs.minigrid.crossing:MiniGridCrossingN2Env",
    max_episode_steps=None,
)
register_env(
    "atlas_rl/minigrid-crossing-n3-v0",
    "atlas_rl.envs.minigrid.crossing:MiniGridCrossingN3Env",
    max_episode_steps=None,
)
register_env(
    "atlas_rl/minigrid-crossing-n1-safe-v0",
    "atlas_rl.envs.minigrid.crossing:MiniGridCrossingN1SafeEnv",
    max_episode_steps=None,
)
register_env(
    "atlas_rl/minigrid-crossing-n2-safe-v0",
    "atlas_rl.envs.minigrid.crossing:MiniGridCrossingN2SafeEnv",
    max_episode_steps=None,
)
register_env(
    "atlas_rl/minigrid-crossing-n3-safe-v0",
    "atlas_rl.envs.minigrid.crossing:MiniGridCrossingN3SafeEnv",
    max_episode_steps=None,
)
register_env(
    "atlas_rl/minigrid-simplecrossing-n1-v0",
    "atlas_rl.envs.minigrid.crossing:MiniGridSimpleCrossingN1Env",
    max_episode_steps=None,
)
register_env(
    "atlas_rl/minigrid-simplecrossing-n2-v0",
    "atlas_rl.envs.minigrid.crossing:MiniGridSimpleCrossingN2Env",
    max_episode_steps=None,
)
register_env(
    "atlas_rl/minigrid-simplecrossing-n3-v0",
    "atlas_rl.envs.minigrid.crossing:MiniGridSimpleCrossingN3Env",
    max_episode_steps=None,
)
register_env(
    "atlas_rl/minigrid-simplecrossing-easy-n1-v0",
    "atlas_rl.envs.minigrid.crossing:MiniGridSimpleCrossingEasyN1Env",
    max_episode_steps=None,
)
register_env(
    "atlas_rl/minigrid-simplecrossing-easy-n2-v0",
    "atlas_rl.envs.minigrid.crossing:MiniGridSimpleCrossingEasyN2Env",
    max_episode_steps=None,
)
register_env(
    "atlas_rl/minigrid-simplecrossing-easy-n3-v0",
    "atlas_rl.envs.minigrid.crossing:MiniGridSimpleCrossingEasyN3Env",
    max_episode_steps=None,
)
register_env(
    "atlas_rl/minigrid-dynamic-obstacles-5x5-v0",
    "atlas_rl.envs.minigrid.dynamic_obstacles:MiniGridDynamicObstacles5x5Env",
    max_episode_steps=None,
)
register_env(
    "atlas_rl/minigrid-dynamic-obstacles-6x6-v0",
    "atlas_rl.envs.minigrid.dynamic_obstacles:MiniGridDynamicObstacles6x6Env",
    max_episode_steps=None,
)
register_env(
    "atlas_rl/minigrid-dynamic-obstacles-8x8-v0",
    "atlas_rl.envs.minigrid.dynamic_obstacles:MiniGridDynamicObstacles8x8Env",
    max_episode_steps=None,
)
register_env(
    "atlas_rl/minigrid-dynamic-obstacles-16x16-v0",
    "atlas_rl.envs.minigrid.dynamic_obstacles:MiniGridDynamicObstacles16x16Env",
    max_episode_steps=None,
)
register_env(
    "atlas_rl/minigrid-gotodoor-5x5-v0",
    "atlas_rl.envs.minigrid.goto:MiniGridGoToDoor5x5Env",
    max_episode_steps=None,
)
register_env(
    "atlas_rl/minigrid-gotodoor-6x6-v0",
    "atlas_rl.envs.minigrid.goto:MiniGridGoToDoor6x6Env",
    max_episode_steps=None,
)
register_env(
    "atlas_rl/minigrid-gotodoor-8x8-v0",
    "atlas_rl.envs.minigrid.goto:MiniGridGoToDoor8x8Env",
    max_episode_steps=None,
)
register_env(
    "atlas_rl/minigrid-gotoobject-6x6-n2-v0",
    "atlas_rl.envs.minigrid.goto:MiniGridGoToObject6x6N2Env",
    max_episode_steps=None,
)
register_env(
    "atlas_rl/minigrid-fetch-5x5-n2-v0",
    "atlas_rl.envs.minigrid.fetch:MiniGridFetch5x5N2Env",
    max_episode_steps=None,
)
register_env(
    "atlas_rl/minigrid-fetch-6x6-n2-v0",
    "atlas_rl.envs.minigrid.fetch:MiniGridFetch6x6N2Env",
    max_episode_steps=None,
)
register_env(
    "atlas_rl/minigrid-fetch-8x8-n3-v0",
    "atlas_rl.envs.minigrid.fetch:MiniGridFetch8x8N3Env",
    max_episode_steps=None,
)
register_env(
    "atlas_rl/minigrid-putnear-6x6-n2-v0",
    "atlas_rl.envs.minigrid.fetch:MiniGridPutNear6x6N2Env",
    max_episode_steps=None,
)
register_env(
    "atlas_rl/minigrid-putnear-8x8-n3-v0",
    "atlas_rl.envs.minigrid.fetch:MiniGridPutNear8x8N3Env",
    max_episode_steps=None,
)
